### PR TITLE
Contribution

### PR DESCRIPTION
**Pull request by damiepsz3**
Hey, here is the code, that we worked the other day

### CODE REVIEW

**Comment by sunsheeppoplar** [comment]
:wave:

**Comment by sunsheeppoplar** [comment]
Looking back at this, @damiepsz3, I don't think you ever pushed to your branch. I don't see any of your changes!

**Comment by damiepsz3** [comment]
Hey you were right! I forgot to push my commits into the branch, sorry!

**Comment by sunsheeppoplar** [comment]
Looks like the site is in need a redesign @damiepsz3, thanks for this PR many years ago 😱  - thinking about using React Hooks now!

**Pull request closed without merging**
